### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cdiggins** [BoyBaykiller/IDKEngine#2]
Hello, very impressive work. Thanks for sharing it, and the excellent write up. What do you think about allowing people to use your code under the MIT license?

**Comment by BoyBaykiller** [comment]
Hello @cdiggins and thank you for the kind words.
Sure, people can use my code under the MIT license.

May I know why you are asking?
Is my shitty spaghetti OpenGL code going to end up in the next big game engine 😄
